name: Testing

on:
  pull_request:
    types: [opened]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn run nx format:check
      - run: yarn run nx affected -t lint test build --configuration=ci

  format-write:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 18
      - run: yarn install
      - run: yarn run nx format:write
