name: Testing

on:
  pull_request:
    types: [opened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          node-version: 18
      - run: bun install
      - run: bun run nx run-many --target=lint --projects=web-akreditasi,web-evaluasi,web-lms,web-neo-feeder,web-pegawai,web-pmb-user,web-pmb-admin,web-siakad,web-sisfo-akuntansi,web-sisfo-aset,web-sisfo-bendahara,web-sisfo-keuangan,web-smart-dashboard,web-tata-usaha,web-tracer-alumni,api,api-auth,api-email,api-file,api-general,api-student,api-user,web-components,api-controllers,entities,api-master,api-models,api-modules,web-modules,api-models,web-providers,api-services,web-services,utilities,api-strategies,api-guard,web-layouts

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          node-version: 18
      - run: bun install
      - run: bun prisma generate
      - run: bun run nx run-many --target=build --projects=web-akreditasi,web-evaluasi,web-lms,web-neo-feeder,web-pegawai,web-pmb-user,web-pmb-admin,web-siakad,web-sisfo-akuntansi,web-sisfo-aset,web-sisfo-bendahara,web-sisfo-keuangan,web-smart-dashboard,web-tata-usaha,web-tracer-alumni,api,api-auth,api-email,api-file,api-general,api-student,api-user,web-components,api-controllers,entities,api-master,api-models,api-modules,web-modules,api-models,web-providers,api-services,web-services,utilities,api-strategies,api-guard,web-layouts

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          node-version: 18
      - run: bun install
      - run: bun run nx run-many --target=test --projects=web-akreditasi,web-evaluasi,web-lms,web-neo-feeder,web-pegawai,web-pmb-user,web-pmb-admin,web-siakad,web-sisfo-akuntansi,web-sisfo-aset,web-sisfo-bendahara,web-sisfo-keuangan,web-smart-dashboard,web-tata-usaha,web-tracer-alumni,api,api-auth,api-email,api-file,api-general,api-student,api-user,web-components,api-controllers,entities,api-master,api-models,api-modules,web-modules,api-models,web-providers,api-services,web-services,utilities,api-strategies,api-guard,web-layouts
